config/routes.rb
Rails.application.routes.draw do
  root 'menu#index'

  get 'reports/index'
	get	'reports/daily'
  devise_for :users

  resource :reports do
    get 'daily'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
end

app/models/bill_detail.rb
class BillDetail < ApplicationRecord

		def self.bill_detail_summary_by_date(date, store, pos_desc)
				BillDetail.select(:product_id,
                          :product_description,
                          "SUM(billdetail_amount) as billdetail_amount",
                          "SUM(billdetail_net1) as billdetail_net1",
                          "SUM(billdetail_net2) as billdetail_net2",
                          "SUM(billdetail_net3) as billdetail_net3",
                          "SUM(billdetail_net4) as billdetail_net4").where(
                          "billdetail_date = ? AND store_id = ?  AND pos_desc = ?",
                          "#{date}", "#{store}", "#{pos_desc}").group(
                          :product_id, :product_description)
    end

end

app/models/reports/daily.rb
class DailyReport < BillDetail

		def self.bill_detail_summary_by_date(date, store, pos_desc)
				BillDetail.select(:product_id,
                          :product_description,
                          "SUM(billdetail_amount) as billdetail_amount",
                          "SUM(billdetail_net1) as billdetail_net1",
                          "SUM(billdetail_net2) as billdetail_net2",
                          "SUM(billdetail_net3) as billdetail_net3",
                          "SUM(billdetail_net4) as billdetail_net4").where(
                          "billdetail_date = ? AND store_id = ?  AND pos_desc = ?",
                          "#{date}", "#{store}", "#{pos_desc}").group(
                          :product_id, :product_description)
    end

end

app/models/turn_paymethod.rb
class TurnPaymethod < ApplicationRecord
  def self.turn_summary_by_date(date, store, pos_desc)
    
    TurnPaymethod.select(:turn_id).where("date = ? AND store_id = ? AND pos_desc = ?", "#{date}", "#{store}", "#{pos_desc}").pluck(:turn_id)

  end

  def self.daily_summary_by_date(store, turn)
    TurnPaymethod.select(:paymethod_id, :paymethod_description, :system_total, :cashbox_total, :difference).where(:turn_id => "#{turn}")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	before_filter :store_current_location, :unless => :devise_controller?

	private
	  def store_current_location
						    store_location_for(:user, request.url)
		end

	private
		def after_sign_out_path_for(resource)
						     request.referrer || root_path
		end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  before_action :authenticate_user!
				
	def index

		if user_signed_in?


		else
			redirect_to new_user_registration_url
		
	 	end
	end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	before_action :authenticate_user!

	def index
  end

	def daily
    if params[:date]
		@products = BillDetail.bill_detail_summary_by_date(params[:date], params[:store], params[:pos_desc])
    @sum = {
      :net1 => @products.map {|s| s['billdetail_net1']}.reduce(0, :+),
      :net2 => @products.map {|s| s['billdetail_net2']}.reduce(0, :+),
      :net3 => @products.map {|s| s['billdetail_net3']}.reduce(0, :+),
      :net4 => @products.map {|s| s['billdetail_net4']}.reduce(0, :+),
      :amount => @products.map {|s| s['billdetail_amount']}.reduce(0, :+)
    }

    @turns = TurnPaymethod.turn_summary_by_date(params[:date], params[:store], params[:pos_desc])
    @turnpaymethod = TurnPaymethod.daily_summary_by_date(params[:store], @turns.first)
    @sumpay = {
      :system_total => @turnpaymethod.map {|s| s['system_total']}.reduce(0, :+),
      :cashbox_total => @turnpaymethod.map {|s| s['cashbox_total']}.reduce(0, :+),
      :difference => @turnpaymethod.map {|s| s['difference']}.reduce(0, :+),
    }
    end

    @stores = BillDetail.uniq.pluck(:store_id)
    @pos = BillDetail.uniq.pluck(:pos_desc)
	end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Heladom</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<div class="container">
		<div class="jumbotron">
						<p class="notice"><%= notice %> </p>
							<p class="alert"><%= alert %> </p>
							<div class="centro">
		<div class="btn btn-primary">
					<%= link_to('Inicio', root_path) %>
</div>
		<% if user_signed_in? %>
			  <li>
				<%= link_to('Salir', destroy_user_session_path, :method => :delete) %>
		  </li>
		<% else %>
				<div class="btn btn-primary">
		 <li>
				  <%= link_to('Ingresar', new_user_session_path)   %>
		 </li>
	 </div>
		<% end %>

		<%= yield %>
</div>
	</div>
</div>
  </body>
</html>

app/views/menu/index.html.erb
<div>
<h1>HELADOM</h1>
</div>

<div class="container">
  <div class="btn-group">
    <button class="btn">Menu Principal</button>
<button class="btn dropdown-toggle" data-toggle="dropdown">
<span class="caret"></span>
</button>
<ul class="dropdown-menu">
<%= link_to "Reportes", reports_index_url %>
</ul>
</div>
</div>

app/views/reports/_paymethodsummary.html.erb
<table>
    <tr>
      <th>Codigo</th>
      <th>Descripcion</th>
      <th>Total Sistema</th>
      <th>Total Caja</th>
      <th>Diferencia</th>
    </tr>
    <% @turnpaymethod.each do | paymethod | %>
      <tr>
        <td><%= paymethod.paymethod_id %></td>
        <td><%= paymethod.paymethod_description %></td>
        <td><%= paymethod.system_total %></td>
        <td><%= paymethod.cashbox_total %></td>
        <td><%= paymethod.difference %></td>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td><%= @sumpay[:system_total] %></td>
      <td><%= @sumpay[:cashbox_total] %></td>
      <td><%= @sumpay[:difference] %></td>
    </tr>
</table>

app/views/reports/_productsummary.html.erb
<table>
    <tr>
      <th>Codigo</th>
      <th>Descripcion</th>
      <th>Cantidad</th>
      <th>Neto 1</th>
      <th>Neto 2</th>
      <th>Neto 3</th>
      <th>Neto 4</th>
    </tr>
    <% @products.each do | product | %>
      <tr>
        <td><%= product.product_id %></td>
        <td><%= product.product_description %></td>
        <td><%= product.billdetail_amount %></td>
        <td><%= product.billdetail_net1 %></td>
        <td><%= product.billdetail_net2 %></td>
        <td><%= product.billdetail_net3 %></td>
        <td><%= product.billdetail_net4 %></td>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td><%= @sum[:amount] %></td>
      <td><%= @sum[:net1] %></td>
      <td><%= @sum[:net2] %></td>
      <td><%= @sum[:net3] %></td>
      <td><%= @sum[:net4] %></td>
    </tr>
</table>

app/views/reports/daily.html.erb
<% if @products.present? %>
  <%= render "productsummary" %>
<% end %>
<% if @turnpaymethod.present? %>
  <%= render "paymethodsummary" %>
<% end %>
<div class="form-group">
  <%= form_tag(daily_reports_path, method: :get) do %>
  <div class="input-group date" data-provide="datepicker">
    <%= text_field_tag :date, params[:date], id: "datepicker", class: "form-control" %>

  <%= select_tag :store, options_for_select(@stores) %>
  <%= select_tag :pos_desc, options_for_select(@pos) %>
  <% if @turns.present? %>
    <%= select_tag :turns, options_for_select(@turns) %>
  <% end %>
  <div class="contenedor">
  <%= submit_tag "Buscar", class: "btn btn-primary" %>
<% end %>
</div>

app/views/reports/index.html.erb
<h1>Modulo de reportes</h1>
<div class="container">
<div class="btn-group">
  <button class="btn">Seleccion</button>
<button class="btn dropdown-toggle" data-toggle="dropdown">
<span class="caret"></span>
</button>
<ul class="dropdown-menu">
  <%= link_to "Reporte Diario", reports_daily_url %>
</ul>
</div>
</div>